# Generated by Django 5.0.7 on 2024-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_allergy_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allergies",
            field=models.ManyToManyField(blank=True, related_name="users", to="common.allergy"),
        ),
    ]
