# Generated by Django 5.0.7 on 2024-08-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_address_user_nickname_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.IntegerField(choices=[(2, "store"), (1, "user")], default=1),
        ),
    ]
