# Generated by Django 5.0.7 on 2024-07-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menus", "0005_alter_menudetailcategory_allergy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lunch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("total_price", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "store",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LunchMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("lunch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lunch.lunch")),
                ("menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="menus.menu")),
            ],
        ),
        migrations.AddField(
            model_name="lunch",
            name="menus",
            field=models.ManyToManyField(blank=True, through="lunch.LunchMenu", to="menus.menu"),
        ),
        migrations.AddConstraint(
            model_name="lunchmenu",
            constraint=models.UniqueConstraint(fields=("menu", "lunch"), name="unique_lunch_menu"),
        ),
    ]
