# Generated by Django 5.0.7 on 2024-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunch",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lunch",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lunch",
            name="name",
            field=models.CharField(default="도시락", max_length=100),
        ),
    ]
