# Generated by Django 5.0.7 on 2024-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0002_alter_lunch_description_alter_lunch_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunch",
            name="total_kcal",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lunchmenu",
            name="kcal",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lunch",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
