# Generated by Django 5.0.7 on 2024-07-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0003_lunch_total_kcal_lunchmenu_kcal_and_more"),
        ("menus", "0005_alter_menudetailcategory_allergy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunchmenu",
            name="lunch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lunch_menu", to="lunch.lunch"
            ),
        ),
        migrations.AlterField(
            model_name="lunchmenu",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lunch_menu", to="menus.menu"
            ),
        ),
    ]
