# Generated by Django 5.0.7 on 2024-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("kcal", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[("BO", "Bob"), ("GU", "Guk"), ("CH", "Chan"), ("SI", "Side")],
                        default="CH",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
