# Generated by Django 5.0.7 on 2024-07-23 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.CharField(
                choices=[("bo", "bob"), ("gu", "guk"), ("ch", "chan"), ("si", "side")], default="ch", max_length=2
            ),
        ),
        migrations.CreateModel(
            name="MenuDetailCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail_category", models.CharField(max_length=30)),
                ("allergy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="common.allergy")),
                ("menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="menus.menu")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
