# Generated by Django 5.0.7 on 2024-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_alter_menudetailcategory_allergy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.CharField(
                choices=[("bob", "밥"), ("guk", "국"), ("chan", "반찬"), ("side", "사이드")],
                default="chan",
                max_length=4,
            ),
        ),
    ]
