# Generated by Django 5.0.7 on 2024-07-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_allergy_name"),
        ("menus", "0004_alter_menu_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menudetailcategory",
            name="allergy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergy_details",
                to="common.allergy",
            ),
        ),
        migrations.AlterField(
            model_name="menudetailcategory",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="menu_details", to="menus.menu"
            ),
        ),
    ]
