# Generated by Django 5.0.7 on 2024-07-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lunch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_things", models.TextField(blank=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=100)),
                ("is_disposable", models.BooleanField(default=False)),
                ("total_price", models.PositiveIntegerField(default=0, editable=False)),
                ("status", models.IntegerField(choices=[(1, "Completed"), (-1, "Cancelled")], default=1)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.PositiveIntegerField(default=0, editable=False)),
                ("lunch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lunch.lunch")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("order", "lunch"), name="unique_order_lunch"),
        ),
    ]
