# Generated by Django 5.0.7 on 2024-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
