# Generated by Django 5.0.7 on 2024-07-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="request_things",
            new_name="cooking_memo",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_memo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="detail_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
