name: cd.yml
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd /home/ec2-user/oz_03_main-001-BE &&
            git pull origin main &&
            poetry install &&
            sudo systemctl restart gunicorn_green &&
            sleep 10 &&
            status_code=$(curl --unix-socket /home/ec2-user/oz_03_main-001-BE/run/gunicorn_green.sock http://localhost/hello -s -o /dev/null -w "%{http_code}")
            if [ "$status_code" = "200" ]; then
              echo "Green deployment successful (Status code: $status_code)"
              sudo systemctl restart gunicorn_blue
            else
              echo "Green deployment failed (Status code: $status_code)"
              exit 1
            fi
          '
